#use_frameworks!
platform :ios, '9.0'

target 'WYOCWebViewController_Example' do
  pod 'WYOCWebViewController', :path => '../'

  target 'WYOCWebViewController_Tests' do
    inherit! :search_paths

    
  end
end
